version: '3.8'
services:
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: nestjs-api
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=postgres
  #     - REDIS_HOST=redis
  #     - GRPC_HOST=grpc-server
  #   depends_on:
  #     - postgres
  #     - redis
  #     - minio
  postgres:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres_data:
  minio-data:
